### ISSUE TITLE
Implement all ANS core words

### ISSUE THREAD

**Issue by remko** [remko/waforth#4]
Implement all [ANS Core words](http://lars.nocrew.org/dpans/dpans6.htm#6.1)

- [x] >NUMBER
- [x] WORD
- [x] M*
- [x] UM*
- [x] UM/MOD
- [x] FM/MOD
- [x] S>D
- [x] SM/REM
- [x] #
- [x] <#
- [x] #>
- [x] #S
- [x] HOLD
- [x] SIGN
- [x] ENVIRONMENT?
- [x] QUIT
- [x] ABORT
- [x] ABORT"
- [x] ACCEPT
- [x] KEY
- [x] !
- [x] '
- [x] (
- [x] *
- [x] /
- [x] /MOD
- [x] +
- [x] +!
- [x] +LOOP
- [x] ,
- [x] -
- [x] .
- [x] ."
- [x] /
- [x] /MOD
- [x] 0<
- [x] 0=
- [x] 1+
- [x] 1-
- [x] 2!
- [x] 2
- [x] 2/
- [x] 2@
- [x] 2DROP
- [x] 2DUP
- [x] 2OVER
- [x] 2SWAP
- [x] :
- [x] ;
- [x] <
- [x] =
- [x] >
- [x] >BODY
- [x] >IN
- [x] >R
- [x] ?DUP
- [x] @
- [x] ABS
- [x] ALIGN
- [x] ALIGNED
- [x] ALLOT
- [x] AND
- [x] BASE
- [x] BEGIN
- [x] BL
- [x] C!
- [x] C,
- [x] C@
- [x] CELL+
- [x] CELLS
- [x] CHAR
- [x] CHAR+
- [x] CHARS
- [x] CONSTANT
- [x] COUNT
- [x] CR
- [x] CREATE
- [x] DECIMAL
- [x] DEPTH
- [x] DO
- [x] DOES>
- [x] DROP
- [x] DUP
- [x] ELSE
- [x] EMIT
- [x] EVALUATE
- [x] EXECUTE
- [x] EXIT
- [x] FILL
- [x] FIND
- [x] HERE
- [x] I
- [x] IF
- [x] IMMEDIATE
- [x] INVERT
- [x] J
- [x] LEAVE
- [x] LITERAL
- [x] LOOP
- [x] LSHIFT
- [x] MAX
- [x] MIN
- [x] MOD
- [x] MOVE
- [x] NEGATE
- [x] OR
- [x] OVER
- [x] POSTPONE
- [x] R>
- [x] R@
- [x] RECURSE
- [x] REPEAT
- [x] ROT
- [x] RSHIFT
- [x] S"
- [x] SOURCE
- [x] SPACE
- [x] SPACES
- [x] STATE
- [x] SWAP
- [x] THEN
- [x] TYPE
- [x] U.
- [x] U<
- [x] UNLOOP
- [x] UNTIL
- [x] VARIABLE
- [x] WHILE
- [x] XOR
- [x] [
- [x] [']
- [x] [CHAR]
- [x] ]

**Comment by albertvanderhorst** [comment]
If . is implemented without resort to <# etc. and without resort to double precision words, it may be of dubious value to implement those.

ENVIRONMENT can be left out; it is a candidate for obsolescence and almost never used.

All double precision operators are in core just because they were thought needed for number output that was 32 bits in the 16 bit era. 
With those missing implementing >NUMBER may have a very bad cost versus benefit ratio.

What with QUIT ? There must be some read-evaluate-print-loop somewhere. Just call it QUIT and you're done.
So my plea is for a loadable extension, not extending the core itself.

**Comment by remko** [comment]
All words are now implemented. There's still one failing test in the core testsuite that is blocking this issue to be closed. I'll address that soon.

**Comment by remko** [comment]
All core word tests from the standard test suite pass. Closing this issue.
